"""Add linked owner WhatsApp identities

Revision ID: 5910d8c52193
Revises: 14de682c4a5e
Create Date: 2026-09-27 09:51:40.599460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5910d8c52193'
down_revision = '14de682c4a5e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('incoming_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('owner_notified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_foreign_key('fk_incoming_order', 'order', ['order_id'], ['id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_whats_app_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'phone'),
    sa.UniqueConstraint('shop_id', 'user_id')
    )
    with op.batch_alter_table('owner_whats_app_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_whats_app_identity_shop_id'), ['shop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('incoming_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incoming_order', type_='foreignkey')
        batch_op.drop_column('owner_notified')
        batch_op.drop_column('order_id')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_whats_app_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_whats_app_identity_shop_id'))

    op.drop_table('owner_whats_app_identity')
    # ### end Alembic commands ###
